//! Stable error codes for nest-airtable.

pub use nest_error::codes::{
    NEST_AIRTABLE_BATCH_LIMIT_EXCEEDED, NEST_AIRTABLE_INVALID_RESPONSE, NEST_AIRTABLE_RATE_LIMITED,
    NEST_AIRTABLE_REQUEST_FAILED, NEST_AIRTABLE_TABLE_NOT_FOUND, NEST_AIRTABLE_TOKEN_MISSING,
};
