[package]
name = "nest-task"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
description = "Task execution contracts for the Nest framework"

[dependencies]
async-trait = "0.1"
nest-core = { workspace = true  }
nest-error = { workspace = true  }
tracing = "0.1"
serde = { version = "1", features = ["derive"], optional = true }

[features]
default = []
serde = ["dep:serde"]
