//! Stable error code constants for CSV errors.

pub use nest_error::codes::{
    NEST_CSV_DESERIALIZE_FAILED, NEST_CSV_PARSE_FAILED, NEST_CSV_REQUIRED_COLUMN_MISSING,
    NEST_CSV_ROW_LIMIT_EXCEEDED, NEST_CSV_VALIDATION_FAILED, NEST_CSV_WRITE_FAILED,
};
