#!/usr/bin/env bash
# Fetch webOS TV docs and index the webos-tv collection only.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
KNOWLEDGE="${NEST_KNOWLEDGE:-/data/nest-knowledge}"
PYTHON="${ROOT}/.venv/bin/python"
FORCE=0

for arg in "$@"; do
  case "$arg" in
    --force) FORCE=1 ;;
  esac
done

if [[ ! -x "$PYTHON" ]]; then
  echo "ERROR: .venv not found. Run:" >&2
  echo "  python3 -m venv .venv && .venv/bin/pip install -r tools/requirements.txt" >&2
  exit 1
fi

FETCH_ARGS=(--webos-only)
if [[ "$FORCE" -eq 1 ]]; then
  FETCH_ARGS+=(--force)
fi

"${ROOT}/scripts/fetch-knowledge.sh" "${FETCH_ARGS[@]}"

CFG="${ROOT}/tools/knowledge-webos.toml"
cat >"$CFG" <<EOF
# Generated by scripts/fetch-webos-knowledge.sh — webos-tv collection only

[[collections]]
name = "webos-tv"
source = "${KNOWLEDGE}/webos-tv"
extensions = ["md"]
EOF

if ! "$PYTHON" "${ROOT}/tools/setup_database.py" 2>/dev/null; then
  echo "Note: schema setup skipped (tables may already exist)." >&2
fi

echo "Indexing webos-tv collection (OpenAI embeddings)..."
"$PYTHON" "${ROOT}/tools/index_knowledge.py" --config "$CFG"

echo ""
echo "Done. Verify:"
echo "  .venv/bin/python tools/search_knowledge.py \"appinfo.json id\" --collection webos-tv"
echo "  # MCP: search_knowledge_base(query=\"webOSRelaunch\", collection=\"webos-tv\")"
