#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
KNOWLEDGE="${NEST_KNOWLEDGE:-/data/nest-knowledge}"
PYTHON="${ROOT}/.venv/bin/python"
CFG="${ROOT}/tools/knowledge.toml"
SKIP_FETCH=0

for arg in "$@"; do
  case "$arg" in
    --skip-fetch) SKIP_FETCH=1 ;;
  esac
done

if [[ ! -x "$PYTHON" ]]; then
  echo "ERROR: .venv not found. Run:" >&2
  echo "  python3 -m venv .venv && .venv/bin/pip install -r tools/requirements.txt" >&2
  exit 1
fi

if [[ "$SKIP_FETCH" -eq 0 ]]; then
  "${ROOT}/scripts/fetch-knowledge.sh"
fi

if [[ ! -d "$KNOWLEDGE" ]]; then
  echo "ERROR: knowledge directory not found: ${KNOWLEDGE}" >&2
  echo "Run ./scripts/fetch-knowledge.sh or set NEST_KNOWLEDGE." >&2
  exit 1
fi

cat >"$CFG" <<EOF
# Generated by scripts/index-knowledge.sh

[[collections]]
name = "rust-book"
source = "${KNOWLEDGE}/rust/rust-book/src"
extensions = ["md"]

[[collections]]
name = "rust-by-example"
source = "${KNOWLEDGE}/rust/rust-by-example/src"
extensions = ["md"]

[[collections]]
name = "rust-reference"
source = "${KNOWLEDGE}/rust/rust-reference/src"
extensions = ["md"]

[[collections]]
name = "tauri"
source = "${KNOWLEDGE}/tauri/tauri-docs/src/content/docs"
extensions = ["md", "mdx"]

[[collections]]
name = "react"
source = "${KNOWLEDGE}/react/react.dev/src/content"
extensions = ["md"]

[[collections]]
name = "tailwind"
source = "${KNOWLEDGE}/tailwind/tailwindcss.com/src/docs"
extensions = ["md", "mdx"]

[[collections]]
name = "webos-tv"
source = "${KNOWLEDGE}/webos-tv"
extensions = ["md"]
EOF

echo "Knowledge root: ${KNOWLEDGE}"
echo "Config written: ${CFG}"

if ! "$PYTHON" "${ROOT}/tools/setup_database.py"; then
  echo "Trying postgres superuser schema setup..." >&2
  "${ROOT}/scripts/setup-database-postgres.sh"
fi

echo "Indexing knowledge collections (OpenAI embeddings; may take several minutes)..."
exec "$PYTHON" "${ROOT}/tools/index_knowledge.py" --config "$CFG"
