#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
KNOWLEDGE="${NEST_KNOWLEDGE:-/data/nest-knowledge}"
PYTHON="${ROOT}/.venv/bin/python"
CFG="${ROOT}/tools/knowledge.toml"

if [[ ! -x "$PYTHON" ]]; then
  echo "ERROR: .venv not found. Run:" >&2
  echo "  python3 -m venv .venv && .venv/bin/pip install -r tools/requirements.txt" >&2
  exit 1
fi

if [[ ! -d "$KNOWLEDGE" ]]; then
  echo "ERROR: knowledge directory not found: ${KNOWLEDGE}" >&2
  echo "Clone manuals into /data/nest-knowledge or set NEST_KNOWLEDGE." >&2
  exit 1
fi

cat >"$CFG" <<EOF
# Generated by scripts/index-knowledge.sh

[[collections]]
name = "rust-book"
source = "${KNOWLEDGE}/rust/rust-book/src"
extensions = ["md"]

[[collections]]
name = "rust-by-example"
source = "${KNOWLEDGE}/rust/rust-by-example/src"
extensions = ["md"]

[[collections]]
name = "rust-reference"
source = "${KNOWLEDGE}/rust/rust-reference/src"
extensions = ["md"]

[[collections]]
name = "egui"
source = "${KNOWLEDGE}/egui/crates/egui/src"
extensions = ["rs", "md"]

[[collections]]
name = "eframe"
source = "${KNOWLEDGE}/egui/crates/eframe/src"
extensions = ["rs", "md"]

[[collections]]
name = "egui-docs"
source = "${KNOWLEDGE}/egui/docs"
extensions = ["md"]

[[collections]]
name = "webos-tv"
source = "${KNOWLEDGE}/webos-tv"
extensions = ["md"]
EOF

echo "Knowledge root: ${KNOWLEDGE}"
echo "Config written: ${CFG}"

if ! "$PYTHON" "${ROOT}/tools/setup_database.py"; then
  echo "Trying postgres superuser schema setup..." >&2
  "${ROOT}/scripts/setup-database-postgres.sh"
fi

echo "Indexing knowledge collections (OpenAI embeddings; may take several minutes)..."
exec "$PYTHON" "${ROOT}/tools/index_knowledge.py" --config "$CFG"
