[package]
name = "{{app_id}}-tui"
version = "0.1.0"
edition = "2021"
rust-version = "1.75"

[[bin]]
name = "{{app_id}}"
path = "src/main.rs"

[dependencies]
{{app_id}}-core = { path = "../core" }
nest-error = { workspace = true }
nest-logging = { workspace = true }
nest-tui = { workspace = true }
crossterm = { workspace = true }
ratatui = { workspace = true }
