//! Stable error code constants for file errors.

pub use nest_error::codes::{
    NEST_FILE_ABSOLUTE_PATH_DENIED, NEST_FILE_DELETE_FAILED, NEST_FILE_EMPTY_PATH,
    NEST_FILE_NOT_FOUND, NEST_FILE_PARENT_NOT_FOUND, NEST_FILE_PATH_OUTSIDE_ROOT,
    NEST_FILE_PATH_TRAVERSAL_DENIED, NEST_FILE_PERMISSION_DENIED, NEST_FILE_READ_FAILED,
    NEST_FILE_SYMLINK_ESCAPE_DENIED, NEST_FILE_WRITE_FAILED,
};
